### ISSUE TITLE
Duplicate href

### ISSUE THREAD

**Issue by Kidkie** [clineamb/bootstrap-drawer#11]
Example file index.html has duplicate href="#drawerExample" attribute on button. Also duplicate in example on website.

**Comment by Stephan972** [comment]
I posted a PR for the same kind of duplicate in readme.md. See: PR https://github.com/clineamb/bootstrap-drawer/pull/10

**Comment by clineamb** [comment]
Ah, thanks guys, and thanks, @Stephan972 for the update in readme!  I'll be merging the pull request and making the change for the site.
