### ISSUE TITLE
Drawer won't hide

### ISSUE THREAD

**Issue by akluthe** [clineamb/bootstrap-drawer#2]
Using the default examples, I am unable to get the drawer to hide.

Standard data-toggle wont let me hide the menu and neither will calling `$("#drawerExample").drawer('hide')`

Attempting to hide the drawer manually returns my drawer dom object as a result.

Using Chrome 42 on Windows.

Any tips on where to start looking to debug?

**Comment by akluthe** [comment]
Scratch that, a crummy old 3.0.0 bootstrap.js was lurking in my app. An update to 3.3 fixed it.

Thanks.

**Comment by clineamb** [comment]
Haha, no problem! Glad you were able to find the solution quickly. (:
