### ISSUE TITLE
Multiple Drawers Overlap

### ISSUE THREAD

**Issue by westindiantech** [clineamb/bootstrap-drawer#20]
I'm trying to use this with my site and have created three separate drawers but if one drawer is opened and I click on another drawer nav link the one below doesn't close. 

Is there a way a drawer retract back/close when a new one is clicked?

**Comment by clineamb** [comment]
@westindiantech - It'd be helpful to see some code, but just from what you wrote, you're probably going to have to use javascript to manually close other drawers when one is opened.

So...
```
$("#btn-drawer1").click(function() { 
     $("#drawer1").drawer("toggle");
     $("#drawer2").drawer("hide");
     $("#drawer3").drawer("hide");
});
```

And you'd probably do the same for other controls, toggle the one that button goes to, and then hide the others. There are more clever ways to do this, but this is the most straightforward.
