### ISSUE TITLE
<a> tag for drawer button forces page navigation

### ISSUE THREAD

**Issue by koolkao** [clineamb/bootstrap-drawer#21]
I'm trying to use the drawer as a slide-out menu in an Angular powered single-page app.  

This <a> tag however forces the page to navigate 

`<a href="#drawerExample" data-toggle="drawer" aria-foldedopen="false" aria-controls="drawerExample" class="btn btn-info btn-sm btn-raised">Menu</a>`

Can this be customized to a <button> instead? 

thank you

**Comment by clineamb** [comment]
You could do this manaully with a `<button>` using javascript click event.
