### ISSUE TITLE
documentation / demo question

### ISSUE THREAD

**Issue by bkwdesign** [clineamb/bootstrap-drawer#5]
I'm having a little troubles with the nested container drawer.

I'm seeing in this [documentation page](http://clineamb.github.io/bootstrap-drawer/index.html) for `#drawerExample2` that there is an `aria-` tag that looks mal-formed:
`aria-foldedopen"false"`

It literally appears as shown above, a value-pair smushed together without an 'equal' sign in between them.

Is this aria- tag required when implementing?

**Comment by bkwdesign** [comment]
This same malformed `aria-foldedopen"false"` tag also appears in the source code [of this documentation page](http://clineamb.github.io/bootstrap-drawer/javascript.html)

**Comment by clineamb** [comment]
Thanks, I'll take a look, and update later today!
