### ISSUE TITLE
Add to cdn?

### ISSUE THREAD

**Issue by cshanejennings** [clineamb/bootstrap-drawer#8]
any chance you could submit the repo to cdnjs?  Here's a somewhat pre-filled link to the submission form if you feel so inclined.  Makes playing with the lib easier on codepen.io

https://github.com/cdnjs/cdnjs/issues/new?title=%5BRequest%5D%20Add%20_library_name_%20&body=**Library%20name%3A**%20%0A**Git%20repository%20url%3A**%0A**npm%20package%20url(optional)%3A**%20%0A**License(s)%3A**%0A**Official%20homepage%3A**%0A**Wanna%20say%20something?%20Leave%20message%20here%3A**%0A%0A%0A%0A=====================%0ANotes%20from%20cdnjs%20maintainer%3A%0AYou%20are%20welcome%20to%20add%20a%20library%20via%20sending%20pull%20request%2C%0Ait%27ll%20be%20faster%20then%20just%20opening%20a%20request%20issue%2C%0Aand%20please%20don%27t%20forget%20to%20read%20the%20guidelines%20for%20contributing%2C%20thanks!!

**Comment by clineamb** [comment]
(Sorry a bit late!) But thanks so much for this. I'll be sure to do so. (:

**Comment by cshanejennings** [comment]
cheers :)

**Comment by Stephan972** [comment]
I posted two submission requests for bootstrap-drawer:

    * cdnjs: https://github.com/cdnjs/cdnjs/issues/7350
    * webjars: https://github.com/webjars/bootstrap-drawer (link not activated yet as of this writing)

**Comment by clineamb** [comment]
@Stephan972 Thanks, I know I said I'd get to it, but I never got around to doing it because I got caught up in all of their guidelines.  I'll close when we get notified that `bootstrap-drawer` was added/rejected.

**Comment by clineamb** [comment]
Closing this as this plugin is in the process of being added to cdnjs!
