### ISSUE TITLE
Deactivate Background If Open?

### ISSUE THREAD

**Issue by erayerdin** [clineamb/bootstrap-drawer#9]
I did not see anything relevant to that. Is there any way to deactivate for touching or clicking on background while drawer is open? Or is it not supported yet?

**Comment by clineamb** [comment]
The javascript emits an event that you can listen for and you can then trigger adding a class yourself.  Here's quick type-up of what that might look like /w jQuery:

```js
$('#your-drawer').on('shown.bs.drawer', function() {
   $('body').addClass('lock-body-scrolling');
});

$('#your-drawer').on('hidden.bs.drawer', function() {
   $('body').removeClass('lock-body-scrolling');
});

```

You can get more info on [event types here](http://clineamb.github.io/bootstrap-drawer/javascript.html).
